api/urls.py
from typing import Any, Generator
from django.urls import path

from api import views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

app_name = 'api'

urlpatterns = [
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(), name='docs'),

    path('ip/', views.IP_APIView.as_view(), name='ip_address'),
    path('datetime/', views.ServerDateTimeAPIView.as_view(), name='datetime'),
    path('client-datetime/', views.DateTimeAPIView.as_view(), name='client_datetime'),
    path('datetime/seconds/', views.DateTimeSecondsAPIView.as_view(), name='seconds'),
    path('user-list/', views.UserListAPIView.as_view(), name='user_list'),
    path('users/', views.UserListAPIView.as_view(), name='users'),
    path('posts/', views.PostListAPIView.as_view(), name='posts'),
    path('posts/<int:pk>/', views.PostDetailAPIView.as_view(), name='post_detail'),
    path('posts/create/', views.PostCreateAPIView.as_view(), name='post_create'),
    path('posts/fake/<int:count>/', views.FakePostCreateAPIView.as_view(),
         name='post_fake'),

    # HTMX
    path('generate-key/', views.GenerateKeyAPIView.as_view(), name='generate_key'),
    path('search-posts/', views.SearchPostsAPIView.as_view(), name='search_posts'),
    path('test/', views.TestHtmxAPIView.as_view(), name='htmx_test'),
    path('htmx-modal/', views.ModalWindowAPIView.as_view(), name='htmx_modal'),
    path('users/check_username/', views.CheckUsernameAPIView.as_view(), 
         name='check_username'),
    path('users/check_email/', views.CheckEmailAPIView.as_view(), name='check_email'),
    path('get-reply-comments/<int:id>/', views.GetReplyCommentsAPIView.as_view(),
         name='get_reply_comments'),
    path('tabs/<str:text>/', views.HtmxTabsAPIView.as_view(),
         name='htmx_tabs'),
]

app/urls.py
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from app.settings import base
from main.views import NotFoundView
from posts.sitemaps import PostSitemap
from filebrowser.sites import site

urlpatterns = [
    # API
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/', include('api.urls', namespace='api')),
    # SITEMAPS
    path('sitemap.xml', sitemap, {'sitemaps': {'posts': PostSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
    # URLS
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('site-admin/filebrowser/', site.urls),
    path('site-admin/login/', NotFoundView.as_view()),
    path('site-admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='user')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(base.STATIC_URL,
                          document_root=base.STATIC_ROOT)
    urlpatterns += static(base.MEDIA_URL,
                          document_root=base.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts.feeds import LatestPostsFeed
from posts import views
app_name = 'posts'

urlpatterns = [
    path('feed/', LatestPostsFeed(), name='feed'),
    path('search', views.PostListView.as_view(), name='search'),
    path('', views.PostListView.as_view(), name='index'),
    path('scroll/', views.ScrollPostListView.as_view(), 
         name='scroll'),
    path('<slug:type_slug>/', views.PostListView.as_view(), 
         name='type'),
    path('topic/<slug:topic_slug>/', views.PostListView.as_view(), 
         name='topic'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), 
         name='tag'),
    path('detail/<slug:post_slug>/', views.PostDetailView.as_view(), 
         name='detail'),
    path('saves', views.SavedPostListView.as_view(), 
         name='saves'),
    path('random', views.RandomPostsView.as_view(), 
         name='random'),
    path('delete/<slug:post_slug>/', views.DeletePostView.as_view(), 
         name='delete'),
    path('comments/delete/<int:id>/', views.DeletePostCommentView.as_view(),
         name='comment_delete'),
    path('like/<int:post_id>/', views.PostLikeAPIView.as_view(),
         name='post_like'),
    path('dislike/<int:post_id>/', views.PostDislikeAPIView.as_view(),
         name='post_dislike'),
    path('save/<int:post_id>/', views.PostSaveAPIView.as_view(),
         name='post_like'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register-wait/', views.ResetWaitView.as_view(), 
         name='reset_wait'),
    path('confirm/<token>/', views.RegisterConfirmView.as_view(),
         name='register_confirm'),
    path('reset-request/', views.PasswordResetView.as_view(),
         name='password_reset'),
    path('reset-confirm/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<str:username>/', views.ProfileDetailView.as_view(),
         name='detail'),
     path('subscribe/', views.SubscribeToProfileView.as_view(),
         name='subscribe'),
]

posts/models.py
from django.db.models import Model, Manager, Index, PositiveSmallIntegerField, CharField, SlugField, BooleanField, TextField, ImageField, DateTimeField, ForeignKey, ManyToManyField
from django.db.models.signals import post_migrate, pre_delete
from django.db.models import SET_NULL, CASCADE
from django.utils.timezone import now
from django.dispatch import receiver
from django.urls import reverse
from django.contrib import admin

from app.settings.base import MEDIA_ROOT
from users.models import User
from colorfield.fields import ColorField
from django_ckeditor_5.fields import CKEditor5Field
import os


class PostType(Model):
    """
    Модель типів для публікацій.
    """
    name = CharField('Назва', max_length=100, unique=True)
    name_plural = CharField('Назва (однина)', max_length=100)
    slug = SlugField('Slug', max_length=200, unique=True)
    color = ColorField('Колір', format="hexa", default='#FF0000')
    description = CharField('Опис', max_length=300)
    created_date = DateTimeField('Дата', default=now)

    class Meta():
        db_table = 'post_types'
        verbose_name = 'Тип публікації'
        verbose_name_plural = 'Типи публікацій'
        ordering = ['created_date']

    def __str__(self):
        return self.name_plural

    def get_absolute_url(self):
        return reverse('posts:index', kwargs={'type_slug': self.slug})


class PostTopic(Model):
    """
    Модель рубрик для публікацій.
    """
    name = CharField('Назва', max_length=150, unique=True)
    slug = SlugField('Slug', max_length=200, unique=True)
    description = TextField('Опис', max_length=1000, blank=True, null=True)
    is_general = BooleanField('Головна', default=False)
    created_date = DateTimeField('Дата', default=now)

    class Meta():
        db_table = 'post_topics'
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('posts:topic', args=[self.slug])


class PostTag(Model):
    """
    Модель тегів для публікацій.
    """
    name = CharField('Назва', max_length=150, unique=True)
    slug = SlugField('Slug', max_length=200, unique=True)
    description = TextField('Опис', max_length=1000, blank=True, null=True)
    created_date = DateTimeField('Дата', default=now)

    class Meta():
        db_table = 'post_tags'
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'
        ordering = ['name']

    def __str__(self):
        return self.name


class PostPublishedManager(Manager):
    """Усі опубліковані публікації."""

    def get_queryset(self):
        return (super().get_queryset()
                .filter(is_publicated=True)
                .order_by('-created_date'))


class Post(Model):
    """
    Базова модель публікації.
    """
    PUBLISH_STATUS = [
        (False, 'Чернетка'),
        (True, 'Опубліковано'),
    ]
    user = ForeignKey(User, SET_NULL, related_name='posts', null=True,
                      blank=True, verbose_name='Автор')
    type = ForeignKey(PostType, SET_NULL, related_name='posts',
                      null=True, verbose_name='Тип')
    title = CharField('Назва', max_length=130, unique=True)
    slug = SlugField('Slug', max_length=150, unique=True,
                     unique_for_date='created_date')
    summary = CharField('Короткий опис', max_length=200, default='')
    content = CKEditor5Field('Текст', config_name='extends', max_length=50000)
    meta_description = CharField('SEO Інформація', max_length=400,
                                 blank=True, null=True)
    image = ImageField('Зображення', upload_to='images/posts/%Y/%m/%d/')
    detail_image = ImageField('Фон', upload_to='images/posts/%Y/%m/%d/detail/',
                              blank=True, null=True)
    topics = ManyToManyField(PostTopic, related_name='posts',
                             blank=True, verbose_name='Рубрики')
    tags = ManyToManyField(PostTag, related_name='posts',
                           blank=True, verbose_name='Теги')
    is_publicated = BooleanField('Опубліковано', choices=PUBLISH_STATUS,
                                 default=True)
    is_edited = BooleanField('Змінено', default=False)
    created_date = DateTimeField('Дата', auto_now_add=True)
    edit_date = DateTimeField('Дата редагування', auto_now=True,
                              blank=True, null=True)
    likes = ManyToManyField(User, related_name='liked_posts',
                            blank=True, verbose_name='Плюси')
    dislikes = ManyToManyField(User, related_name='disliked_posts',
                               blank=True, verbose_name='Мінуси')
    saves = ManyToManyField(User, related_name='saved_posts',
                            blank=True, verbose_name='В збережених')
    review_pluses = CharField('Плюси (Огляд)', max_length=1000,
                              blank=True, null=True)
    review_minuses = CharField('Мінуси (Огляд)', max_length=1000,
                               blank=True, null=True)
    review_rating = PositiveSmallIntegerField('Рейтинг (Огляд)',
                                              blank=True, null=True)

    objects = Manager()
    published = PostPublishedManager()

    class Meta():
        db_table = 'posts'
        verbose_name = 'Публікація'
        verbose_name_plural = '🟩 Публікації'
        ordering = ['-created_date']
        indexes = [Index(fields=['-created_date', 'slug'])]

    def __str__(self):
        return self.title[:30]

    def get_absolute_url(self):
        return reverse('posts:detail', args=[self.slug])

    @admin.display(description='Плюси')
    def total_likes(self):
        return self.likes.count()

    @admin.display(description='Мінуси')
    def total_dislikes(self):
        return self.dislikes.count()
    
    @admin.display(description='В збережених')
    def total_saves(self):
        return self.saves.count()


class PostCommentActiveManager(Manager):
    """Усі активні коментарі."""

    def get_queryset(self):
        return (super().get_queryset()
                .filter(is_active=True)
                .order_by('-created_date'))


class PostComment(Model):
    """
    Модель коментарів до публікацій.
    """
    post = ForeignKey(Post, CASCADE, related_name='comments',
                      null=True, blank=True, verbose_name='Пост')
    user = ForeignKey(User, CASCADE, related_name='comments',
                      verbose_name='Автор')
    parent = ForeignKey('self', SET_NULL, related_name='childrens',
                        blank=True, null=True, verbose_name="Відповідь на")
    text = CKEditor5Field('Текст', config_name='comments', max_length=1000)
    is_edited = BooleanField('Змінено', default=False)
    created_date = DateTimeField('Дата', auto_now_add=True)
    edit_date = DateTimeField('Дата редагування', auto_now=True,
                              blank=True, null=True)
    likes = ManyToManyField(User, related_name='liked_comments',
                            blank=True, verbose_name='Плюси')
    dislikes = ManyToManyField(User, related_name='disliked_comments',
                               blank=True, verbose_name='Мінуси')
    is_active = BooleanField('Активний', default=True)

    objects = Manager()
    active = PostCommentActiveManager()

    class Meta():
        db_table = 'comments'
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        ordering = ['-created_date']
        indexes = [Index(fields=['-created_date'])]

    def __str__(self):
        return f'({self.user.username}) {self.text[0:22]}'

    def get_absolute_url(self):
        return f"{reverse('posts:detail', args=[self.post.slug])}#comment-{self.id}"

    @admin.display(description='Плюси')
    def total_likes(self):
        return self.likes.count()

    @admin.display(description='Мінуси')
    def total_dislikes(self):
        return self.dislikes.count()


@receiver(pre_delete, sender=Post)
def delete_post(sender, instance: Post, **kwargs):
    instance.tags.clear()
    instance.topics.clear()
    instance.likes.clear()
    instance.dislikes.clear()
    instance.saves.clear()

    if instance.image:
        image_path = MEDIA_ROOT / instance.image.path
        if os.path.exists(image_path):
            os.remove(image_path)


@receiver(post_migrate)
def create_default_post_type_and_topic(sender, **kwargs):
    if not PostType.objects.exists():
        PostType.objects.create(
            name='Новини',
            name_plural='Новина',
            slug='news',
            description='Новини зі світу відеоігор та технологій',
        )

    if not PostTopic.objects.exists():
        PostTopic.objects.create(
            name='Ігрова індустрія',
            slug='igrova-industriya',
            description="Усі публікації пов'язані з усією ігровою індустрією",
        )


# class PostTopicRelation(Model):
#     post = ForeignKey(Post, CASCADE)
#     topic = ForeignKey(PostTopic, CASCADE)

#     class Meta:
#         db_table = 'posts_topics'

# class PostTagRelation(Model):
#     post = ForeignKey(Post, CASCADE)
#     tag = ForeignKey(PostTag, CASCADE)

#     class Meta:
#         db_table = 'posts_tags'

posts/forms.py
from django.forms import Form, CharField, ValidationError

from django_ckeditor_5.widgets import CKEditor5Widget


class CreatePostCommentForm(Form):
    text = CharField(required=True, widget=CKEditor5Widget(
        attrs={'class': 'django_ckeditor_5 comment-editor'}, 
        config_name='comments'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].required = False
    
    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise ValidationError('Коментар не може бути пустим')
        return data

templates/posts/_post_card.html
{% load static humanize main_tags posts_tags %}

{% if post.is_publicated %}
    <div id="post-block" class="row bg-white border-bottom">
        <div class="col pl-4 pr-4 d-flex flex-column position-static">
            <p class="d-inline-block mt-2 mb-2">

                <a href="{{ post.get_absolute_url }}#comments" 
                    class="comments-count text-dark"
                    title="Коментарі {{ post.comments.count }}">
                    <i class="bi bi-chat-right-text"></i> {{ post.comment_count }}
                </a>

                {% if post.type.slug %}
                    <a href="{% url 'posts:type' post.type.slug %}"
                        class="font-weight-bold ml-2"
                        style="color: {{ post.type.color }}">
                        {{ post.type.name }}
                    </a>
                {% endif %}
                
                {% if user.is_staff %}
                    <a href="{% url 'posts:delete' post.slug %}" 
                        class="btn btn-danger ml-5">
                        <i class="bi bi-trash"></i>
                    </a>
                    <!-- onclick="return confirm('Ви впевнені, що хочете видалити цю публікацію?');" -->
                    <a href="{% url 'admin:posts_post_change' post.id %}" 
                        class="btn btn-dark">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                {% endif %} 
            </p>

            <p class="d-inline-block mb-1">
                {% if post.user %} 
                    Автор:
                    <a href="{% url 'user:detail' post.user.username %}" title="{{ post.user.username }}">
                        <b>{{ post.user.get_full_name|default:post.user.username }}</b>
                    </a>
                {% else %}
                    <b>{{ site_main_title }}</b>
                {% endif %} <i class="text-secondary">{{ post.created_date|date:'d E, Y' }}</i>
            </p>
            
            <a href="{% url 'posts:detail' post.slug %}" class="text-dark">
                <h3 class="mb-0">
                    {% autoescape off %}
                        {% if post.headline %}
                            {{ post.headline|truncatechars:55 }}
                        {% else %}
                            {{ post.title|truncatechars:55 }}
                        {% endif %}
                    {% endautoescape %}
                </h3>
            </a>

            <p class="card-text mb-auto">
                {% autoescape off %} 
                    {% if post.bodyline %}
                        {{ post.bodyline|truncatechars:170 }}
                    {% else %}
                        {{ post.content|truncatechars:100|clear_tags|bleach_linkify }}
                    {% endif %}
                {% endautoescape %}
            </p>
        </div>

        {% if post.review_rating and post.type.pk == 2 %}
            <div class="card-review-rating col-auto pr-0 p-2">
                <a href="{% url 'posts:detail' post.slug %}"
                    style="background: {{ post.review_rating|rating_to_color }};">
                    {{ post.review_rating }}
                </a>
            </div>
        {% endif %}
        
        <div class="post-image col-auto pr-0 p-2">
            <a href="{{ post.get_absolute_url }}">
                {% if post.image %}
                    <img class="bd-placeholder-img" src="{{ post.image.url }}" 
                        width="220" height="220">
                {% else %}
                    <img class="bd-placeholder-img" src="{% static 'images/not_found_image.png' %}" 
                        width="220" height="220">
                {% endif %}
            </a>
        </div>
    </div>
{% endif %}

templates/posts/detail.html
{% extends 'base.html' %}
{% load static cache humanize main_tags posts_tags %}

{% block css %}
    <meta property="og:title" content="{{ post.title }}" />
    <meta property="og:description" 
        content="{{ post.content|truncatechars:60|clear_tags|bleach_linkify }}" />
    {% if post.image %}
        <meta property="og:image" content="{{ post.image.url }}" />
    {% endif %}
{% endblock %}

{% block content %}

<div class="row bg-white mt-3 rounded">
    <div class="post-content col-md-9">
        <div class="card">
            <div class="row">
                {% if not post.detail_image %}
                    <div class="col-md-3">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="img-thumbnail" data-bs-toggle="modal"
                                data-bs-target="#imageModal1">
                        {% else %}
                            <img src="{% static 'images/not_found_image.png' %}" class="img-thumbnail">
                        {% endif %}
                    </div>
                {% endif %}
                
                <div class="col-md-7">
                    <h2 class="mt-3">{{ post.title }}</h2>
                    <p class="mt-3">
                        {% if post.user %}
                            Автор: 
                            <a href="{% url 'user:detail' post.user.username %}">
                                <b>{{ post.user.get_full_name }}</b>
                            </a>
                        {% else %}
                            <b>{{ site_main_title }}</b>
                        {% endif %}
                        
                        <a href="{% url 'posts:type' post.type.slug %}"
                            class="font-weight-bold ml-2"
                            style="color: {{ post.type.color }}">
                            {{ post.type }}
                        </a>
                        
                        <a href="#comments" 
                            class="comments-count text-dark float-right"
                            title="Коментарі: {{ post.comments.count }}">
                            <i class="bi bi-chat-right-text"></i> 
                            {{ post.comments.count }}
                        </a>
                        <a class="ml-3" 
                            title="Перегляди: {{ total_views }}">
                            👁️ {{ total_views }}
                        </a>
                    </p>
                    <p class="text-secondary">
                        {{ post.created_date|naturalday }}
                        {% if user.is_staff %}
                            <a href="{% url 'posts:delete' post.slug %}" 
                                class="btn btn-danger float-right"
                                onclick="return confirm('Ви впевнені, що хочете видалити цю публікацію?');">
                                <i class="bi bi-trash"></i>
                            </a>
                            <a href="{% url 'admin:posts_post_change' post.id %}" 
                                class="btn btn-dark float-right">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                        {% endif %}
                        
                        <i class="float-right mr-3">
                            <div class="popup share-link-copy"
                                onclick="copyShareLink()">
                                <i class="bi bi-share-fill"></i>
                                <text>Поділитися: </text>
                                <span class="popuptext" id="share-popup">Посилання скопійовано!</span>
                            </div>
                            <a href="https://www.facebook.com/share.php?u={{ request.build_absolute_uri }}">
                                <i class="bi bi-facebook"></i></a>
    
                            <a href="https://x.com/intent/post?url={{ request.build_absolute_uri }}&text={{ post.title }}">
                                <i class="bi bi-twitter"></i></a>
                        </i>
                    </p>
                </div>
                
                {% if post.detail_image %}
                    <img src="{{ post.detail_image.url }}" 
                        class="img-thumbnail" 
                        data-bs-toggle="modal">
                {% endif %}
            </div>
    
            <div class="ck-content">
                {{ post.content|safe }}
            </div>

            {% if post.review_rating %}
                <div class="review-rating" 
                    style="background: {{ post.review_rating|rating_to_color }}; 
                    {% if user_agent.is_mobile %}font-size: 40px;{% endif %}">
                    {{ post.review_rating }}
                    <div class="ml-5">
                        {{ post.review_rating|rating_to_text }}
                    </div>
                </div>
                <div class="review row mt-2">
                    <div class="review-pluses col-md-6 text-right">
                        <h5>Вдалося</h5>
                        <p>
                            <i>{{ post.review_pluses|linebreaks }}</i>
                        </p>
                    </div>
                    <div class="review-minuses col-md-6 text-left">
                        <h5>Не вдалося</h5>
                        <p>
                            <i>{{ post.review_minuses|linebreaks }}</i>
                        </p>
                    </div>
                </div>
                <div class="review-genre">
                    <p class="text-center"> 
                        Жанри: |
                        Компанії: 
                    </p>
                </div>
            {% endif %}
            
            <div class="post-tags m-2 p-2 bg-light">
                <i>
                    <p class="d-inline fst-italic">
                        Рубрики: |
                        {% for topic in post.topics.all %}
                            <a href="{% url 'posts:topic' topic.slug %}"    
                                title="
                                {% if topic.description %}
                                    {{ topic.description }}
                                {% else %}
                                    {{ topic.name }}
                                {% endif %}
                                    ">{{ topic }}</a>
                                    |
                        {% endfor %}
                    </p>
                    <p>
                        Теги:
                        {% for tag in post.tags.all %}
                            <a href="{% url 'posts:tag' tag.slug %}"    
                                title="
                                {% if tag.description %}
                                    {{ tag.description }}
                                {% else %}
                                    {{ tag.name }}
                                {% endif %}
                                    "> {{ tag }}</a>{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                </i>
            </div>
            <div class="post-buttons m-2">
                {% with users_like=post.likes.all users_dislike=post.dislikes.all users_save=post.saves.all %}
                    <block class="post-likes ml-5 mr-3" 
                        
                        hx-get="/posts/like/{{ post.pk }}" 
                        hx-trigger="click"
                        hx-target=".post-likes">
                        {% csrf_token %}
                        <block title="{% if request.user in users_like %}
                        Зняти лайк{% else %}
                        Поставити лайк{% endif %}">
                            <i class="bi bi-plus-square{% if request.user in users_like %}-fill{% endif %}"></i>
                            {{ users_like.count }} Лайк
                        </block>
                    </block>
                    <block class="post-dislikes mr-3" 
                        hx-get="/posts/dislike/{{ post.pk }}" 
                        hx-trigger="click"
                        hx-target=".post-dislikes">
                        {% csrf_token %}
                        <block title="{% if request.user in users_dislike %}
                        Зняти дизлайк{% else %}
                        Поставити дизлайк{% endif %}">
                            <i class="bi bi-dash-square{% if request.user in users_dislike %}-fill{% endif %}"></i>
                            {{ users_dislike.count }} Дизлайк
                        </block>
                    </block>
                    <block class="post-saves btn btn-dark" 
                        title="В закладки"
                        hx-get="/posts/save/{{ post.pk }}" 
                        hx-trigger="click"
                        hx-target=".post-saves">
                        {% csrf_token %}
                        <block title="{% if request.user in users_save %}
                        Вилучити зі збережених{% else %}
                        Додати в збережені{% endif %}">
                            <i class="bi bi-bookmark{% if request.user in users_save %}-check-fill{% endif %}"></i> 
                        </block>
                    </block>
                {% endwith %}
            </div>
        </div>
    </div>

    {% with post_list=latest_posts %}
        <div class="latest_posts col-md-3 mt-4">
            <p>
                <a href="{% url 'posts:feed' %}">
                RSS стрічка новин
                </a>
            </p>
            <h4>Останні {{ post.type.name|lower }}</h4>
            {% include 'posts/_other_post_list.html' %}
        </div>
    {% endwith %}
</div>

<div class="post-comments mb-3">
    <div class="row bg-white mt-3 overflow-hidden flex-md-row shadow-sm h-md-250 position-relative">
        <div class="col d-flex flex-column position-static">
            <h4 id="comments" class="pt-3 pb-2">Коментарі {{ post.comments.count }}</h4>
            
            <form id="comment-form" method="post" action="{% url 'posts:detail' post.slug %}">
                {% csrf_token %}
                {{ form.text }}
                {{ form.media }}
                <div class="d-flex align-items-center">
                    <button type="submit" class="btn btn-primary mt-2 mb-2 mr-3">
                        Надіслати
                    </button>
                    <div id="comment-auth-warning" 
                        class="alert alert-danger mt-3 p-2" 
                        style="display: none;">
                        <a href="{% url 'users:login' %}">Увійдіть</a>, щоб написати коментар
                    </div>
                </div>
            </form>
            {% if form.text.errors %}
                <div class="alert alert-danger alert-dismissible fade show">
                    {{ form.text.errors }}
                </div>
            {% endif %}
        </div>
    </div>
        
    {% include 'posts/_comment_tree.html' with comments=post.comments.all %}
</div>

{% with modal_image=post.image modal_title=post.title %}
    {% include '_modal_image_preview.html' %}
{% endwith %}

{% endblock %}

{% block script %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var form = document.getElementById('comment-form');

        if (!{% if user.is_authenticated %}true{% else %}false{% endif %}) 
        {
            form.onsubmit = function(event) {
                event.preventDefault();
                document.getElementById('comment-auth-warning').style.display = 'block';
            };
        }
    });

    function copyShareLink() {
        navigator.clipboard.writeText(window.location.href);
        var popup = document.getElementById("share-popup");
        popup.classList.toggle("show");
    }    
</script>

{% endblock %}

templates/posts/feed_description.html
<![CDATA[<div style="margin: 5px 5% 10px 5%;"><img src="http://{{ site }}{{ obj.image.url }}" width="640" height="360" title="" alt="" /></div><div></div><div>&nbsp;</div><div><em>Source: <a href="{{ obj.get_absolute_url }}" target="_blank" data-wpel-link="internal">{{ site_main_title }}</a></em></div>]]>