api/urls.py
from typing import Any, Generator
from django.urls import path

from api import views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

app_name = 'api'

urlpatterns = [
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(), name='docs'),

    path('ip/', views.IP_APIView.as_view(), name='ip_address'),
    path('datetime/', views.ServerDateTimeAPIView.as_view(), name='datetime'),
    path('client-datetime/', views.DateTimeAPIView.as_view(), name='client_datetime'),
    path('datetime/seconds/', views.DateTimeSecondsAPIView.as_view(), name='seconds'),
    path('user-list/', views.UserListAPIView.as_view(), name='user_list'),
    path('users/', views.UserListAPIView.as_view(), name='users'),
    path('posts/', views.PostListAPIView.as_view(), name='posts'),
    path('posts/<int:pk>/', views.PostDetailAPIView.as_view(), name='post_detail'),
    path('posts/create/', views.PostCreateAPIView.as_view(), name='post_create'),
    path('posts/fake/<int:count>/', views.FakePostCreateAPIView.as_view(),
         name='post_fake'),

    # HTMX
    path('generate-key/', views.GenerateKeyAPIView.as_view(), name='generate_key'),
    path('search-posts/', views.SearchPostsAPIView.as_view(), name='search_posts'),
    path('test/', views.TestHtmxAPIView.as_view(), name='htmx_test'),
    path('htmx-modal/', views.ModalWindowAPIView.as_view(), name='htmx_modal'),
    path('users/check_username/', views.CheckUsernameAPIView.as_view(), 
         name='check_username'),
    path('users/check_email/', views.CheckEmailAPIView.as_view(), name='check_email'),
    path('get-reply-comments/<int:id>/', views.GetReplyCommentsAPIView.as_view(),
         name='get_reply_comments'),
    path('tabs/<str:text>/', views.HtmxTabsAPIView.as_view(),
         name='htmx_tabs'),
]

app/urls.py
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from app.settings import base
from main.views import NotFoundView
from posts.sitemaps import PostSitemap
from filebrowser.sites import site

urlpatterns = [
    # API
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/', include('api.urls', namespace='api')),
    # SITEMAPS
    path('sitemap.xml', sitemap, {'sitemaps': {'posts': PostSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
    # URLS
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('site-admin/filebrowser/', site.urls),
    path('site-admin/login/', NotFoundView.as_view()),
    path('site-admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='user')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(base.STATIC_URL,
                          document_root=base.STATIC_ROOT)
    urlpatterns += static(base.MEDIA_URL,
                          document_root=base.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('test', views.TestFunctionsView.as_view(), name='test'),
    path('decode', views.DecodeTextView.as_view(), name='decode_text'),
    path('test-email', views.TestEmailView.as_view(), name='test_email'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path

from posts.feeds import LatestPostsFeed
from posts import views
app_name = 'posts'

urlpatterns = [
    path('feed/', LatestPostsFeed(), name='feed'),
    path('search', views.PostListView.as_view(), name='search'),
    path('', views.PostListView.as_view(), name='index'),
    path('scroll/', views.ScrollPostListView.as_view(), 
         name='scroll'),
    path('<slug:type_slug>/', views.PostListView.as_view(), 
         name='type'),
    path('topic/<slug:topic_slug>/', views.PostListView.as_view(), 
         name='topic'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), 
         name='tag'),
    path('detail/<slug:post_slug>/', views.PostDetailView.as_view(), 
         name='detail'),
    path('saves', views.SavedPostListView.as_view(), 
         name='saves'),
    path('random', views.RandomPostsView.as_view(), 
         name='random'),
    path('delete/<slug:post_slug>/', views.DeletePostView.as_view(), 
         name='delete'),
    path('comments/delete/<int:id>/', views.DeletePostCommentView.as_view(),
         name='comment_delete'),
    path('like/<int:post_id>/', views.PostLikeAPIView.as_view(),
         name='post_like'),
    path('dislike/<int:post_id>/', views.PostDislikeAPIView.as_view(),
         name='post_dislike'),
    path('save/<int:post_id>/', views.PostSaveAPIView.as_view(),
         name='post_like'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register-wait/', views.ResetWaitView.as_view(), 
         name='reset_wait'),
    path('confirm/<token>/', views.RegisterConfirmView.as_view(),
         name='register_confirm'),
    path('reset-request/', views.PasswordResetView.as_view(),
         name='password_reset'),
    path('reset-confirm/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<str:username>/', views.ProfileDetailView.as_view(),
         name='detail'),
     path('subscribe/', views.SubscribeToProfileView.as_view(),
         name='subscribe'),
]

templates/_advertisement.html
{% load static cache main_tags %}

{% cache 5 advertisement %}
    {% for advertisement in advertisements %}
        <div class="advertisement" style="{{ advertisement.css_style|bleach_xss|safe }}"> 
            {% if user.is_staff %}
                <a href="/admin/main/announcement/">
                    <h4>{{ advertisement.description|bleach_xss|safe }}</h4>
                </a>
            {% else %}
                <h4>{{ advertisement.description|bleach_xss|safe }}</h4>
            {% endif %}
        </div>
    {% endfor %}
{% endcache %}

templates/_footer.html
{% load static cache %}

<footer class="position-relative d-flex flex-wrap justify-content-between align-items-center py-3 border-top bg-white">
    <div class="col-md-4 d-flex align-items-center">
        
        <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
            <svg class="bi" width="30" height="24">
                <use xlink:href="#bootstrap"></use>
            </svg>
        </a>
        <i>
            <span class="mb-3 mb-md-0 text-body-secondary">
                &copy; {{ current_year }} - {{ site_main_title }}
            </span>
            <a href="{% url 'main:about' %}" class="ml-2 link-body-emphasis">
                Про сайт
            </a>
        </i>
    </div>
</footer>

templates/_header.html
{% load static cache main_tags %}

<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'main:index' %}">
            <i class="bi bi-controller"></i>
            {{ site_main_title }}
        </a>
   
        <button class="navbar-toggler" 
            type="button" data-bs-toggle="collapse" 
            data-bs-target="#navbarCollapse" 
            aria-controls="navbarCollapse" 
            aria-expanded="false" 
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">

                {% cache 120 type %}
                    {% for type in post_types %}
                        <li class="nav-item">
                            <a href="{% url 'posts:type' type.slug %}" 
                                class="nav-link px-2 link-body-emphasis"
                                style="color: {{ type.color }};">
                                {{ type.name }}</a>
                        </li>
                    {% endfor %}
                {% endcache %}

                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}{% if request.path != '/register/' and request.path != '/login/'  %}?next={{ request.path }}{% endif %}" 
                            class="nav-link px-2 link-body-emphasis">
                            Увійти</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:register' %}" class="nav-link px-2 link-body-emphasis">
                            Реєстрація</a>
                    </li>
                {% else %}
                    <li class="nav-item dropdown mega-menu-item">
                        <a class="nav-link dropdown-toggle" href="" 
                            id="navbarDarkDropdownMenuLink"
                            role="button"
                            data-bs-toggle="dropdown" 
                            aria-expanded="false">
                            Акаунт </a>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li>
                                <a class="dropdown-item" 
                                    href="{% url 'user:detail' user.username %}">
                                    Профіль 
                                    {% if user.first_name %}
                                        ({{ user.first_name }}{% if user.last_name %} {{ user.last_name }}{% endif %})
                                    {% elif user.last_name %}
                                        ({{ user.last_name }})
                                    {% else %}
                                        ({{ user.username }})
                                    {% endif %}
                                </a>
                            </li>
                            <li><a href="{% url 'posts:saves' %}" 
                                class="dropdown-item">
                                Збережене</a></li>
                            <li><a href="{% url 'users:profile' %}"
                                class="dropdown-item">
                                Налаштування</a></li>
                            {% if user.is_staff %}
                            <li><a href="{% url 'api:docs' %}"
                                class="dropdown-item">
                                Api Docs</a></li>
                            {% endif %}
                            <hr class="dropdown-divider">
                            <li><a href="{% url 'user:logout' %}?next={{ request.path }}"
                                class="dropdown-item" >
                                Вийти</a></li>
                        </ul>
                    </li>

                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a href="{% url 'admin:index' %}" 
                                class="nav-link px-2 link-body-emphasis"
                                title="Адмін панель">
                                Адмін <i class="bi bi-kanban-fill"></i></a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'api:post_fake' 10 %}" 
                                class="nav-link px-2 link-body-emphasis"
                                title="Додати тестові публікації">
                                Fake <i class="bi bi-facebook"></i></a>
                        </li>
        
                        <li class="nav-item">
                            <a href="{% url 'admin:index' %}posts/post/add/" 
                                class="nav-link px-2 link-body-emphasis"
                                title="Створити публікацію">
                                Add <i class="bi bi-file-earmark-plus-fill"></i></a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>

            <form class="form-inline mt-2 mt-md-0" role="search" action="{% url 'posts:search' %}" method="GET">
                <input 
                    value="{{ request.GET.q }}"
                    name="q"
                    class="form-control mr-sm-2" 
                    type="text" 
                    placeholder="Пошук..." 
                    aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" 
                    type="submit" 
                    hidden>Знайти</button>
            </form>
        </div>
    </nav>
</header>

templates/_modal_image_preview.html
{% load static %}

<div class="modal fade" id="imageModal1" tabindex="-1" aria-labelledby="imageModal1Label"
    aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="imageModal1Label">{{ modal_title }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Закрити">x</button>
            </div>
            {% if modal_image %}
            <div class="modal-body">
                <img src="{{ modal_image.url }}" class="img-fluid" alt="{{ modal_title }}">
            </div>
            {% endif %}
        </div>
    </div>
</div>

templates/_modal_window.html
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{{ modal_title }}</h5>
        </div>
        <div class="modal-body">
            <p>{{ modal_body }}</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                {{ modal_close_text|default:'Вийти' }}
            </button>
        </div>
    </div>
</div>

templates/_notifications.html
{% load static humanize main_tags %}

<div class="notifications-container text-center">

    <!-- {% if form.non_field_errors %}
        <div class="container mt-4">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                        {{ form.non_field_errors }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %} -->

    <div class="notification"> 
        {% if messages %}
            {% for message in messages %}
                <div id="notification"
                    class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} fade show custom-shadow" 
                    role="alert">
                    {{ message.message|clear_tags|safe }}
                </div>
            {% endfor %}
        {% else %}
            <div id="jq-notification" class="position-relative start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
                {{ message }}
            </div>
        {% endif %}
    </div>

    <!-- <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                {% if messages %}
                    {% for message in messages %}
                        <div id="notification" 
                            class="position-relative start-50 translate-middle-x z-3 alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} fade show custom-shadow" 
                            role="alert">
                            {{ message.message|bleach_xss|safe }}
                        </div>
                    {% endfor %}
                {% else %}
                    <div id="jq-notification" class="position-relative start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            </div>
        </div>
    </div> -->
</div>

templates/_paginator.html
{% load main_tags %}

{% if page_obj.paginator.num_pages > 1 %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">
                <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                    <a class="page-link {% if page_obj.has_previous %} bg-dark text-white {% endif %}"
                        href="{% if page_obj.has_previous %}?{% change_params page=page_obj.previous_page_number %}{% else %}#{% endif %}">
                        Назад
                    </a>
                </li>

                {% for page in page_obj.paginator.page_range %}
                    {% if user_agent.is_mobile %}
                        {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}

                            <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                                <a class="page-link {% if page_obj.number == page %} bg-dark text-white {% else %} bg-light text-dark {% endif %}" 
                                    href="?{% change_params page=page %}">{{ page }}</a>
                            </li>

                        {% endif %}
                    {% else %}
                        {% if page >= page_obj.number|add:-5 and page <= page_obj.number|add:5 %}
                            
                            <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                                <a class="page-link {% if page_obj.number == page %} bg-dark text-white {% else %} bg-light text-dark {% endif %}" 
                                    href="?{% change_params page=page %}">{{ page }}</a>
                            </li>

                        {% endif %}
                    {% endif %}
                {% endfor %}

                <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                    <a class="page-link {% if page_obj.has_next %} bg-dark text-white {% endif %}"
                        href="{% if page_obj.has_next %}?{% change_params page=page_obj.next_page_number %}{% else %}#{% endif %}">
                        Вперед
                    </a>
                </li>
            </div>
        </ul>
    </nav>
{% endif %}

templates/base.html
{% load static cache %}

<!DOCTYPE html>
<html lang="uk" prefix="og: //ogp.me/ns#">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/post-card.css' %}" />
    <link rel="stylesheet" href="{% static 'css/post-detail.css' %}" />
    <link rel="stylesheet" href="{% static 'css/ck-content.css' %}" />
    <link rel="stylesheet" href="{% static 'css/popup-text.css' %}" />
    <script async charset="utf-8" src="{% static 'js/ck/embed-platform.js' %}"></script>

    {% block css %}
    {% endblock %}

    {% block title %}
        <title>
            {% if title %}
                {{ title }} - {{ site_main_title }}
            {% else %}
                {{ site_main_title }}
            {% endif %}
        </title>
    {% endblock %}
</head>

<body>
    <div class="wrapper">
        {% include '_header.html' %}

        <main class="main">
            {% block advertisement %}
            {% endblock %}
            
            {% include '_notifications.html' %}

            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </main>

        {% include '_footer.html' %}
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/ck/embedly-card.js' %}"></script>
    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script src="{% static 'js/htmx-ws.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    
    {% block script %}
    {% endblock %}
</body>

</html>