api/urls.py
from typing import Any, Generator
from django.urls import path

from api import views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

app_name = 'api'

urlpatterns = [
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(), name='docs'),

    path('ip/', views.IP_APIView.as_view(), name='ip_address'),
    path('datetime/', views.ServerDateTimeAPIView.as_view(), name='datetime'),
    path('client-datetime/', views.DateTimeAPIView.as_view(), name='client_datetime'),
    path('datetime/seconds/', views.DateTimeSecondsAPIView.as_view(), name='seconds'),
    path('user-list/', views.UserListAPIView.as_view(), name='user_list'),
    path('users/', views.UserListAPIView.as_view(), name='users'),
    path('posts/', views.PostListAPIView.as_view(), name='posts'),
    path('posts/<int:pk>/', views.PostDetailAPIView.as_view(), name='post_detail'),
    path('posts/create/', views.PostCreateAPIView.as_view(), name='post_create'),
    path('posts/fake/<int:count>/', views.FakePostCreateAPIView.as_view(),
         name='post_fake'),

    # HTMX
    path('generate-key/', views.GenerateKeyAPIView.as_view(), name='generate_key'),
    path('search-posts/', views.SearchPostsAPIView.as_view(), name='search_posts'),
    path('test/', views.TestHtmxAPIView.as_view(), name='htmx_test'),
    path('htmx-modal/', views.ModalWindowAPIView.as_view(), name='htmx_modal'),
    path('users/check_username/', views.CheckUsernameAPIView.as_view(), 
         name='check_username'),
    path('users/check_email/', views.CheckEmailAPIView.as_view(), name='check_email'),
    path('get-reply-comments/<int:id>/', views.GetReplyCommentsAPIView.as_view(),
         name='get_reply_comments'),
    path('tabs/<str:text>/', views.HtmxTabsAPIView.as_view(),
         name='htmx_tabs'),
]

app/urls.py
from django.contrib.sitemaps.views import sitemap
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from app.settings import base
from main.views import NotFoundView
from posts.sitemaps import PostSitemap
from filebrowser.sites import site

urlpatterns = [
    # API
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='docs'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/', include('api.urls', namespace='api')),
    # SITEMAPS
    path('sitemap.xml', sitemap, {'sitemaps': {'posts': PostSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
    # URLS
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('site-admin/filebrowser/', site.urls),
    path('site-admin/login/', NotFoundView.as_view()),
    path('site-admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='user')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]
    urlpatterns += static(base.STATIC_URL,
                          document_root=base.STATIC_ROOT)
    urlpatterns += static(base.MEDIA_URL,
                          document_root=base.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register-wait/', views.ResetWaitView.as_view(), 
         name='reset_wait'),
    path('confirm/<token>/', views.RegisterConfirmView.as_view(),
         name='register_confirm'),
    path('reset-request/', views.PasswordResetView.as_view(),
         name='password_reset'),
    path('reset-confirm/<token>/', views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/<str:username>/', views.ProfileDetailView.as_view(),
         name='detail'),
     path('subscribe/', views.SubscribeToProfileView.as_view(),
         name='subscribe'),
]

users/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.db.models import Count
from django.contrib.auth.tokens import default_token_generator, PasswordResetTokenGenerator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib import auth, messages
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView
from django.views import View

from app.settings.base import EMAIL_HOST_USER, APP_NAME, MEDIA_ROOT
from main.services import create_random_image
from posts.models import Post
from users.tasks import celery_send_mail, celery_clear_user_token
from users.models import Profile, Subscribe, User
from users.forms import UserEditForm, ProfileEditForm, UserLoginForm, UserRegisterForm, ResetTokenForm, ResetPasswordForm, SetNewPasswordForm
from users.services import generate_token


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('user:reset_wait')

    def form_valid(self, form: UserRegisterForm):

        email = form.cleaned_data['email']
        user, created = User.objects.get_or_create(email=email)

        if created or not user.is_active:
            token = generate_token()
            activation_url = self.request.build_absolute_uri(
                reverse_lazy('user:register_confirm', kwargs={'token': token}))

            # celery_send_mail.delay(subject, message, html_message, email, False)
            
            send_mail(
                subject=f'Код активації акаунта ({APP_NAME})',
                message=f'({APP_NAME}) Код активації акаунта: {token}',
                html_message=f"""
                    <h2>Код активації акаунта ({APP_NAME})</h2>
                    <p>Код: <b>{token}</b></p>
                    <p>або перейдіть за посиланням <a href="{activation_url}">{activation_url}</a></p>""",
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
                fail_silently=False)

            user.is_active = False
            user.activation_key = token
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.username = form.cleaned_data['username']
            user.set_password(form.cleaned_data['password1'])
            user.save()
            # clear_activation_key.apply_async((user.pk,), countdown=300)

        messages.success(self.request,
                         'На ваш email надіслано лист з посиланням для підтвердження акаунта')
        return super().form_valid(form)

    def form_invalid(self, form: UserRegisterForm):
        return self.render_to_response(self.get_context_data(form=form))


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'

    def get_success_url(self):
        next_url = self.request.GET.get(
            'next') or self.request.POST.get('next')
        if next_url:
            return next_url

        return reverse('user:profile')


class ProfileView(LoginRequiredMixin, View):
    template_name = 'users/profile.html'

    def get(self, request: HttpRequest):
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

        context = {
            'form': user_form,
            'profile_form': profile_form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserEditForm(data=request.POST, instance=request.user)
        profile_form = ProfileEditForm(data=request.POST,
                                       instance=request.user.profile,
                                       files=request.FILES)

        if form.is_valid() and profile_form.is_valid():
            form.save()
            profile_form.save()
            messages.success(request, 'Дані користувача успішно змінено')

        context = {
            'form': form,
            'profile_form': profile_form,
        }
        return render(request, self.template_name, context)


class LogoutView(View):

    def get(self, request: HttpRequest):
        next_page = request.GET.get('next', 'main:index')

        if request.user.is_authenticated:
            messages.success(request, 'Ви вийшли з акаунта')
            auth.logout(request)

        return redirect(next_page)


class ResetWaitView(FormView):
    template_name = 'users/reset_wait.html'
    form_class = ResetTokenForm
    token: str

    def form_valid(self, form):
        self.token = form.cleaned_data['token']
        self.success_url = reverse_lazy(
            'user:register_confirm', kwargs={'token': self.token})
        return super().form_valid(form)


class RegisterConfirmView(View):
    def get(self, request: HttpRequest, token):
        try:
            user = User.objects.get(activation_key=token)

        except User.DoesNotExist:
            messages.error(
                request, 'Неправильний код активації або код застарів')
            return redirect('user:reset_wait')

        except Exception:
            messages.error(request, 'Помилка активації')
            return redirect('user:reset_wait')
        
        user.is_active = True
        user.activation_key = None

        image_path = f'images/users/{user.id}/avatar/{user.username}.png'
        create_random_image(MEDIA_ROOT / image_path)
        user.profile.avatar = image_path
        
        user.save()

        auth.login(request, user, 'django.contrib.auth.backends.ModelBackend')
        messages.success(request, 'Ви успішно зареєструвались')
        
        return redirect('user:profile')


class PasswordResetView(FormView):
    template_name = 'users/password_reset.html'
    form_class = ResetPasswordForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form: ResetPasswordForm):
        email = form.cleaned_data['email']
        user = User.objects.filter(email=email).first()

        if user:
            token = generate_token()
            user.activation_key = token
            user.save()
            reset_url = self.request.build_absolute_uri(
                reverse_lazy('user:password_reset_confirm', kwargs={'token': token}))

            subject = f'Відновлення паролю на сайті ({APP_NAME})'
            message = f'({APP_NAME}) Щоб відновити пароль перейдіть за посиланням: {reset_url}'
            html_message = f"""
                <h2>Відновлення паролю на сайті ({APP_NAME})</h2>
                <p>Щоб відновити пароль перейдіть за посиланням: {reset_url}</p>
            """
            # celery_send_mail.delay(subject, message, html_message, email, False)

            send_mail(
                subject=subject,
                message=message,
                html_message=html_message,
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
                fail_silently=False)

            messages.success(
                self.request, 'Перевірте свою електронну пошту для відновлення паролю.')
        else:
            messages.error(
                self.request, 'Користувача з такою електронною поштою не знайдено.')

        return super().form_valid(form)


class PasswordResetConfirmView(FormView):
    template_name = 'users/password_reset_confirm.html'
    form_class = SetNewPasswordForm
    success_url = reverse_lazy('user:profile')

    def get(self, request, *args, **kwargs):
        token = kwargs.get('token')
        user = self.get_user_by_token(token)

        if user is None:
            messages.error(
                self.request, 'Це посилання для зміни пароля застаріло')
            return redirect('main:index')

        return super().get(request, *args, **kwargs)

    def form_valid(self, form: SetNewPasswordForm):
        token = self.kwargs.get('token')
        user = self.get_user_by_token(token)
        if user:
            user.set_password(form.cleaned_data['password1'])
            user.activation_key = None
            user.is_active = True
            user.save()
            messages.success(
                self.request, 'Пароль успішно змінено. Увійдіть з новим паролем.')
        else:
            messages.error(
                self.request, 'Неправильний токен для зміни пароля.')
        return super().form_valid(form)

    def get_user_by_token(self, token):
        try:
            return User.objects.get(activation_key=token)
        except User.DoesNotExist:
            return None


class ProfileDetailView(DetailView):

    def get(self, request: HttpRequest, username):
        user = get_object_or_404(User, username=username)
        posts = (Post.published
                 .filter(user=user)
                 .select_related('type', 'user')
                 .annotate(comment_count=Count('comments'))
                 )
        total_followers = user.profile.followers.count()
        followers = user.profile.followers.all()
        context = {
            'title': user.username,
            'detail_user': user,
            'posts': posts,
            'total_followers': total_followers, 
            'followers': followers,
        }
        return render(request, 'users/user_detail.html', context)


class SubscribeToProfileView(View):

    def get(self, request: HttpRequest):
        user_id = request.GET.get('id')
        action = request.GET.get('action')
        reditect_back = request.META.get('HTTP_REFERER', 'main:index')

        if user_id and action:
            try:
                user_from: Profile = request.user.profile
                user_to: Profile = User.objects.get(id=user_id).profile

                if user_from == user_to:
                    messages.error(request, f'Ви не можете підписатися на себе')

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Вхід - {{ site_main_title }}</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="container mt-5 mb-3">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mx-3 rounded custom-shadow">
                
                <form class="form-signin" method="POST">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                            <p>{{ form.non_field_errors }}</p>
                        </div>
                    {% endif %}
                    
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}

                    <h1 class="h3 mb-3 fw-normal text-center">Вхід</h1>
                
                    <div class="form-floating">
                        <label for="id_username" class="form-label">Email</label>
                        <input type="email" class="form-control"
                            value="{{ form.username.value|default:'' }}"
                            id="id_username" 
                            name="username" 
                            placeholder="Введіть ваш Email"
                            autofocus="true"
                            required>
                    </div>
                    <div class="form-floating mt-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input type="password" class="form-control"
                            value="{{ form.password.value|default:'' }}"
                            id="id_password"
                            name="password"
                            placeholder="Введіть ваш пароль" 
                            required>
                    </div>
                    <div class="form-floating mt-3">
                        {{ form.captcha }}
                        {% if form.captcha.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.captcha.errors }}</div>
                        {% endif %}
                    </div>
                    <button class="w-100 btn btn-lg btn-primary mt-3" type="submit">Увійти</button>
                </form>

                {% include 'users/_or_social.html' %}

                <div class="forgot-password mt-2 text-center">
                    <a href="{% url 'user:password_reset' %}" class="dark">Забули пароль?</a> | 
                    <a href="{% url 'user:register' %}" class="dark">Створити акаунт</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/password_reset.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Відновити пароль - {{ site_main_title }}</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Відновити пароль</h2>
                <p></p>
                <form action="{% url 'user:password_reset' %}" method="POST">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                            <p>{{ form.non_field_errors }}</p>
                        </div>
                    {% endif %}

                    <div class="mb-3">
                        <label for="id_email" class="form-label">Email</label>
                        <input type="email" class="form-control" 
                            autofocus="true"
                            id="id_email" 
                            name="email" 
                            value="{{ form.email.value|default:'' }}" 
                            placeholder="Введіть ваш Email" 
                            required>
                    </div>

                    <div class="mb-3">
                        {{ form.captcha }}
                        {% if form.captcha.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.captcha.errors }}</div>
                        {% endif %}
                    </div>
                    
                    <button type="submit" class="btn btn-dark btn-block">Надіслати</button> 
                </form>

                <div class="mt-3">
                    <a href="{% url 'user:register' %}" class="dark">Створити акаунт</a>
                </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Змінити пароль - {{ site_main_title }}</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Змінити пароль</h2>

                <form method="POST">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                            <p>{{ form.non_field_errors }}</p>
                        </div>
                    {% endif %}

                    <div class="col-md-6 mb-3">
                        <label for="id_password1" class="form-label">Новий пароль</label>
                        <input type="password" class="form-control" 
                            value="{{ form.password1.value|default:'' }}" 
                            id="id_password1"
                            name="password1"
                            placeholder="Введіть новий пароль" 
                            required>
                        {% if form.password1.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="col-md-6 mb-3">
                        <label for="id_password2" class="form-label">Повторити пароль</label>
                        <input type="password" class="form-control" 
                            value="{{ form.password2.value|default:'' }}"
                            id="id_password2"
                            name="password2"
                            placeholder="Підтвердіть пароль" 
                            required>
                        {% if form.password2.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="col-md-6 mb-3">

                        {{ form.captcha }}

                        {% if form.captcha.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.captcha.errors }}</div>
                        {% endif %}
                    </div>
                    
                    <button type="submit" class="btn btn-dark btn-block">Змінити пароль</button> 
                </form>

                <div class="mt-3">
                    <a href="{% url 'user:register' %}" class="dark">Створити акаунт</a>
                </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load main_tags %}

{% block title %}
    <title>{{ user.username }} - Профіль</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-5">
        <div class="bg-white mt-5 mb-4 p-4 rounded">
            <h3 class="text-center mb-4">Профіль користувача</h3>
            
            <form id="profile-form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="row">
                    <div class="col-md-12 mb-3 text-center">
                        {% if user.profile.avatar %}
                            <img src="{{ user.profile.avatar.url }}"
                                class="img-fluid rounded-circle"
                                title="{{ user.profile.avatar.name|basename }}"
                                alt="{{ user.profile.avatar.name|basename }}" 
                                style="max-width: 150px;">
                            <p class="small">зараз: {{ user.profile.avatar.name|basename }}</p>
                        {% else %}
                            <img src="{% static 'images/baseavatar.jpg' %}"
                                alt="Аватар" class="img-fluid rounded-circle"
                                style="max-width: 150px;">
                        {% endif %}
                        
                        <input type="file" class="form-control"
                            title="Виберіть фото профілю"
                            id="id_avatar"
                            name="avatar"
                            accept="image/*">

                        {% if profile_form.avatar.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">
                                {{ profile_form.avatar.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_first_name" class="form-label">Ім'я*</label>
                        <input type="text" class="form-control" 
                            value="{{ form.first_name.value|default:'' }}" 
                            id="id_first_name"
                            name="first_name"
                            placeholder="Введіть ваше ім'я" 
                            required>

                        {% if form.first_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">
                                {{ form.first_name.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_last_name" class="form-label">Прізвище</label>
                        <input type="text" class="form-control" 
                            value="{{ form.last_name.value|default:'' }}"     
                            id="id_last_name"
                            name="last_name"
                            placeholder="Введіть ваше прізвище">

                        {% if form.last_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">
                                {{ form.last_name.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_username" class="form-label">Ім'я користувача*</label>
                        <input type="text" class="form-control" 
                            value="{{ form.username.value|default:'' }}" 
                            id="id_username"
                            name="username"
                            placeholder="Введіть ваше ім'я користувача" 
                            required>

                        {% if form.username.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">
                                {{ form.username.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_email" class="form-label">Email*</label>
                        <input type="email" class="form-control" 
                            value="{{ form.email.value|default:'' }}" 
                            id="id_email"
                            name="email"
                            placeholder="Введіть ваш email" 
                            required
                            readonly>

                        {% if form.email.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">
                                {{ form.email.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_phone_number" class="form-label">Номер телефону* (+380-XX-XXX-XX-XX)</label>
                        <input type="tel" class="form-control" pattern="(\+380\d{9}|0\d{9})"
                            value="{{ profile_form.phone_number.value|default:'' }}" 
                            id="id_phone_number"
                            name="phone_number"
                            placeholder="+380-XX-XXX-XX-XX">

                        {% if profile_form.phone_number.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">
                                {{ profile_form.phone_number.errors }}</div>
                        {% endif %}
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_date_of_birth" class="form-label">День народження</label>
                        <input type="date" class="form-control"
                            value="{{ profile_form.date_of_birth.value|default:'' }}" 
                            id="id_date_of_birth"
                            name="date_of_birth">

                        {% if profile_form.date_of_birth.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">
                                {{ profile_form.date_of_birth.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="col-md-12 mb-3">
                        <label for="id_bio" class="form-label">Опис</label>
                        <textarea class="form-control" 
                            id="id_bio" 
                            name="bio" 
                            placeholder="Опишіть себе">{{ profile_form.bio.value|default:'' }}</textarea>
                    
                        {% if profile_form.bio.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">
                                {{ profile_form.bio.errors }}</div>
                        {% endif %}
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Зберегти</button>
                
                <a class="btn btn-dark float-right" href="{% url 'user:detail' user.username %}">
                    Дивитись профіль
                </a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/reset_wait.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Підтвердження - {{ site_main_title }}</title>
{% endblock %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mx-3 rounded custom-shadow">
                <h5 class="text-center mb-4">На ваш email надіслано лист з посиланням для підтвердження акаунта</h5>
                <form method="POST">
                    {% csrf_token %}

                    {% if form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                            <p>{{ form.non_field_errors }}</p>
                        </div>
                    {% endif %}
                    
                    <div class="mb-3">
                        <label for="id_token" class="form-label">Код активації</label>
                        <input type="text" class="form-control" 
                            autofocus="true"
                            id="id_token" 
                            name="token"
                            placeholder="Введіть код активації" 
                            required>
                    </div>
                    
                    <div class="mb-3">
                        {{ form.captcha }}
                        {% if form.captcha.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.captcha.errors }}</div>
                        {% endif %}
                    </div>
                    
                    <button type="submit" class="btn btn-dark btn-block">Надіслати</button> 
                </form>

                <div class="mt-3">
                    <a href="{% url 'user:register' %}" class="dark">Створити акаунт</a> |
                    <a href="{% url 'user:login' %}" class="dark">Увійти</a>
                </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}